name: UAV
version: '${project.version}'
main: io.github.dominic.uavp2.UAV
api-version: '1.20'
authors: [Dominic Young]
description: A UAV drone to stalk someone

commands:
  activate:
    description: Stalk someone
  uav:
    description: The help command
